### ISSUE TITLE
Reduce number of required command line arguments

### ISSUE THREAD

**Issue by MeerkatPerson** [simra-project/osmColoring#5]
At the moment, ~10 command line arguments need to be provided in order to run Main.kt. This seems overkill especially when considering that most of these will be the same for every region (in- and output directories) or at least for every run for a specific region (all the other arguments). 

**Suggestion**:

1. Have a file from which the arguments are pulled upon running Main.kt (analogous to config.py in osmPreparation). This way, only the parameter "region" has to be provided and the other values can be edited in the aforementioned file as desired before running Main.kt.
2. Include (empty) I/O directories in the project (with a .placeholder for git) so that the user doesn't have to figure out for herself where to read from/write to.

**Comment by MoeweX** [comment]
Default values for almost all arguments are defined in here: https://github.com/simra-project/osmColoring/blob/master/src/main/kotlin/main/CommandLineArguments.kt

If some defaults are missing, feel free to add them :), but I think the only mandatory input is the region name, e.g., it is sufficient to supply `-r Leipzig`.

**Comment by MoeweX** [comment]
If you think there are still thinks open for discussion, just re-open the issue @MeerkatPerson
